const bugs = [
  {
    id: 1,
    title: "Button overlap on mobile",
    description: "Submit and Cancel buttons overlap on screens narrower than 375px, making both impossible to tap.",
    category: "Layout",
    severity: "high",
    date: "2026-07-01",
  },
  {
    id: 2,
    title: "Dropdown clips behind modal",
    description: "Select dropdowns inside a modal dialog are clipped by the modal's overflow:hidden, hiding options.",
    category: "Z-index / Overflow",
    severity: "high",
    date: "2026-07-03",
  },
  {
    id: 3,
    title: "Focus ring invisible on dark background",
    description: "The default browser focus outline is invisible against the dark header, failing WCAG 2.1 AA contrast requirements.",
    category: "Accessibility",
    severity: "medium",
    date: "2026-07-05",
  },
  {
    id: 4,
    title: "Tooltip flickers on hover",
    description: "Moving the cursor slowly toward a tooltip causes it to appear and disappear rapidly due to a mouseleave/mouseenter loop.",
    category: "Interaction",
    severity: "low",
    date: "2026-07-08",
  },
  {
    id: 5,
    title: "Text truncation breaks mid-word",
    description: "Long product names are cut with overflow:hidden but without text-overflow:ellipsis, producing an abrupt mid-character cut.",
    category: "Typography",
    severity: "medium",
    date: "2026-07-10",
  },
  {
    id: 6,
    title: "Sticky header covers anchor targets",
    description: "Navigating to an in-page anchor scrolls the target element behind the fixed header, hiding the heading.",
    category: "Layout",
    severity: "medium",
    date: "2026-07-12",
  },
];
